apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: 9000
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: 9001