CREATE DATABASE IF NOT EXISTS admin_systems;
CREATE DATABASE IF NOT EXISTS admin_hrm;
CREATE DATABASE IF NOT EXISTS admin_media;
CREATE DATABASE IF NOT EXISTS admin_posts;
CREATE DATABASE IF NOT EXISTS daklak_translation;
CREATE DATABASE IF NOT EXISTS daklak_db;
CREATE DATABASE IF NOT EXISTS admin_workflow;
CREATE DATABASE IF NOT EXISTS admin_document;
