apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: 5672
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: 15672