replicaCount: 1

image:
  repository: thanhtran1993/daklak-user-service
  tag: "latest"
  pullPolicy: Always

migration:
  image:
    repository: thanhtran1993/daklak-user-service-migration
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

database:
  name: admin_systems
  host: mysql.infra.svc.cluster.local
  port: 3306
  user: root
  rootPassword: mypassword

env:
  NODE_ENV: production

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi