replicaCount: 2

image:
  repository: thanhtran1993/daklak-user-service
  tag: "latest"        # ⚠️ CI sẽ override bằng commit SHA
  pullPolicy: IfNotPresent

migration:
  image:
    repository: thanhtran1993/daklak-user-service-migration
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

database:
  host: mysql.infra.svc.cluster.local
  port: 3306
  name: admin_systems

# ❗ KHÔNG để password ở đây nữa
secret:
  create: true
  name: user-service-secret
  data:
    DATABASE_URL: "mysql://root:mypassword@mysql.infra.svc.cluster.local:3306/admin_systems"

env:
  NODE_ENV: production

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi