apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-5"


type: Opaque
data:
  # Ví dụ: mysql://root:pass@mariadb:3306/db_name mã hóa base64
  DATABASE_URL: {{ printf "mysql://%s:%s@%s:%d/%s" .Values.database.user .Values.database.rootPassword .Values.database.host (int .Values.database.port) .Values.database.name | b64enc }}
  