apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-config
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  my.cnf: |
{{ .Values.mysql.config | indent 4 }}
