replicaCount: 1

image:
  repository: your-dockerhub/backend
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

database:
  name: admin_systems
  host: mysql.infra.svc.cluster.local
  port: 3306
  user: root
  rootPassword: mypassword

env:
  NODE_ENV: production

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi