architecture: standalone

auth:
  rootPassword: "mypassword"
  username: "daklak_user"
  password: "mypassword"
  database: "daklak_db"

initdbScripts:
  init-dbs.sql: |
    CREATE DATABASE IF NOT EXISTS admin_systems;
    CREATE DATABASE IF NOT EXISTS admin_posts;
    CREATE DATABASE IF NOT EXISTS admin_hrm;
    CREATE DATABASE IF NOT EXISTS admin_media;
    CREATE DATABASE IF NOT EXISTS daklak_translation;

    GRANT ALL PRIVILEGES ON admin_systems.* TO 'daklak_user'@'%';
    GRANT ALL PRIVILEGES ON admin_posts.* TO 'daklak_user'@'%';
    GRANT ALL PRIVILEGES ON admin_hrm.* TO 'daklak_user'@'%';
    GRANT ALL PRIVILEGES ON admin_media.* TO 'daklak_user'@'%';
    GRANT ALL PRIVILEGES ON daklak_translation.* TO 'daklak_user'@'%';
    FLUSH PRIVILEGES;

primary:
  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001

  persistence:
    enabled: false
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClass: hostpath   # FIX LỖI PVC

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi