# ==========================================
# Builder Stage
# ==========================================
FROM node:22-alpine AS builder

WORKDIR /app

COPY apps/api-gateway/package*.json ./

RUN npm ci

COPY apps/api-gateway/ ./
COPY shared/protos ./shared/protos

RUN npm run build

# Loại bỏ devDependencies
RUN npm prune --omit=dev


# ==========================================
# Runner Stage
# ==========================================
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Nếu gateway dùng gRPC proto files
COPY --from=builder /app/shared/protos ./shared/protos

ENV PROTO_PATH=/app/shared/protos

# Security
RUN addgroup -S app && adduser -S app -G app

RUN chown -R app:app /app

USER app

EXPOSE 8080

CMD ["node", "dist/src/main.js"]