name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/daklak-chart/**'
      - '.github/workflows/cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # ☸️ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      # 🔐 Giải mã KUBECONFIG từ Secret
      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      # ⎈ Setup Helm
      - name: Setup Helm
        uses: azure/setup-helm@v4

      # 🚀 Deploy bằng Helm (Deploy toàn bộ chart daklak-chart)
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install daklak ./deploy/daklak-chart \
            --namespace production \
            --create-namespace \
            --values ./deploy/daklak-chart/values.yaml
